apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: sanyi-cluster
  region: eu-central-1
  version: "1.23"

nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    desiredCapacity: 2